---
title: "Population, 7 June 2024"
output: 
  html_document:
    css: Wil_style.css
    theme: default
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
always_allow_html: yes
---


```{r setup1, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(bslib)
library(DT)
library(dplyr)
library(gglaplot)
library(ggplot2)
library(data.table)
library(tidyr)
library(stringr)
library(tidyverse)
library(plotly)
library(sf)
library(htmlwidgets)
library(knitr)
library(lubridate)
library(maps)
library(scales)
library(forcats)


data_dir <- 'DATA/'
chart_dir <- 'CHARTS/'

#colour_palette <- gla_colour_palette()[c(3,6,2,4,5,7,1)]

# Disable scientific notation
options(scipen=999)

```


```{r setup2, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}


## Import population data

input_2011and2021data <- fread(paste0(data_dir,"mye_tables_EandW_LAs_2011and2021only.csv"))%>% 
  data.frame()

input_2001and2011data <- fread(paste0(data_dir,"mye_tables_EandW_LAs_2001and2011only.csv"))%>% 
  data.frame()

input_region_lookup_tabledata <- fread(paste0(data_dir,"Local_Authority_District_to_Region_(December_2020)_Lookup_in_England.csv"))%>% 
  data.frame()

```


```{r setup8, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

#-----------------------------------------------------------------------
## Compare 0 year olds in 2011 with 10 year olds in 2021

LA_2001zero <- input_2001and2011data %>% 
  mutate(pop2001zero = X2001) %>%
  filter(age == 0) %>%  
  data.frame() 

LA_2011ten <- input_2001and2011data %>% 
  mutate(pop2011ten = X2011) %>%
  filter(age == 10) %>%  
  data.frame()

# Merge the two datasets

LA_2001and2011 <- LA_2001zero  %>%
  left_join(LA_2011ten, by=c("ladcode18"="ladcode18", "laname18"="laname18", "sex" = "sex")) %>% 
  data.frame() 

# calculate change
LA_2001and2011_agezeroand10_change <- LA_2001and2011 %>% 
  group_by(ladcode18, laname18) %>% 
  summarise(Sum2011ten = sum(pop2011ten), 
            Sum2001zero = sum(pop2001zero)) %>%
  mutate(Change_2001to2011 = ((Sum2011ten - Sum2001zero)*100/Sum2001zero)) %>%
  drop_na() %>%
  data.frame()

#--------------------------------------------------------------------------------

## Compare 0 year olds in 2011 with 10 year olds in 2021

LA_2011zero <- input_2011and2021data %>% 
  mutate(pop2011zero = X2011) %>%
  filter(age == 0) %>%  
  data.frame() 

LA_2021ten <- input_2011and2021data %>% 
  mutate(pop2021ten = X2021) %>%
  filter(age == 10) %>%  
  data.frame()

# Merge the two datasets

LA_2011and2021 <- LA_2011zero  %>%
  left_join(LA_2021ten, by=c("ladcode21"="ladcode21", "laname21"="laname21", "sex" = "sex")) %>% 
  data.frame() 

# calculate change
LA_2011and2021_agezeroand10_change <- LA_2011and2021 %>% 
  group_by(ladcode21, laname21) %>% 
  summarise(Sum2021ten = sum(pop2021ten), 
            Sum2011zero = sum(pop2011zero)) %>%
  mutate(Change_2011to2021 = ((Sum2021ten - Sum2011zero)*100/Sum2011zero)) %>%
  drop_na() %>%
  data.frame()



```


```{r fig_pop_change_cohort_8, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Map of cohort change from 2011 to 2021 

# Import LA boundaries for England and Wales 

borough_boundaries20 <-
  st_read("C:/Geographical/LA_UK_boundaries/Local_Authority_Districts_(December_2020)_UK_BGC.shp", quiet = TRUE)

londonmap6_diverge = c('#b2182b','#ef8a62','#fddbc7','#f7f7f7','#d1e5f0','#67a9cf')

# Match boundary data with pop data and create categories for mapping

change_2011to2021_geog <- LA_2011and2021_agezeroand10_change %>% 
  left_join(borough_boundaries20, by=c("ladcode21"="LAD20CD")) %>%
  mutate(Perc_Cat = cut(Change_2011to2021, breaks = c(-45, -28, -16, -5, 5, 24, 50),
                             right=FALSE,
                             labels = c(" -45.0 - -28.01",
                                        " -28.0 - -16.01",
                                        " -16.0 - -5.01",
                                        " -5.0  -  4.99",
                                        "  5.0  - 23.99",
                                        " 24.0  - 50.00"))) %>%
  data.frame()

change_2011to2021_map <- change_2011to2021_geog %>%
  ggplot()+
  # geom_point(aes(x=BNG_E, y=BNG_N,
  #                text = paste("LA name: ", laname21,
  #                             "<br>Percent change: ",
  #                             formatC(Change_2011to2021, format="f", big.mark=",", digits=2))),
  #            alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
  geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.2, colour = "black")+
  #ggla_sf()+
  #theme_gla()+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank())+
  scale_fill_manual(values = londonmap6_diverge) + 
  labs(title= "Cohort change between 2011 and 2021 (zeros to ten year olds) in London", 
       subtitle = "Using MYE instead of census data",
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
  labs(fill = "")

change_2011to2021_map


```


```{r fig_pop_change_cohort_9, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Map of cohort change from 2001 to 2011 

# Import LA boundaries for England and Wales - trying with 2015 data
borough_boundaries15 <-
  st_read("C:/Geographical/LA_UK_boundaries/Local_Authority_Districts_(December_2015)_Boundaries.shp", quiet = TRUE)


# Match boundary data with pop data and create categories for mapping

change_2001to2011_geog <- LA_2001and2011_agezeroand10_change %>% 
  left_join(borough_boundaries15, by=c("ladcode18"="lad15cd")) %>%
  mutate(Perc_Cat = cut(Change_2001to2011, breaks = c(-45, -28, -16, -5, 5, 24, 50),
                             right=FALSE,
                             labels = c(" -45.0 - -28.01",
                                        " -28.0 - -16.01",
                                        " -16.0 - -5.01",
                                        " -5.0  -  4.99",
                                        "  5.0  - 23.99",
                                        " 24.0  - 50.00"))) %>%
  data.frame()

change_2001to2011_map <- change_2001to2011_geog %>%
  ggplot()+
  # geom_point(aes(x=BNG_E, y=BNG_N,
  #                text = paste("LA name: ", laname21,
  #                             "<br>Percent change: ",
  #                             formatC(Change_2011to2021, format="f", big.mark=",", digits=2))),
  #            alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
  geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.2, colour = "black")+
  #ggla_sf()+
  #theme_gla()+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank())+
  scale_fill_manual(values = londonmap6_diverge) + 
  labs(title= "Cohort change between 2001 and 2011 (zeros to ten year olds) in London", 
       subtitle = "Using MYE instead of census data",
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
  labs(fill = "")
change_2001to2011_map

```

```{r fig_pop_change_cohort_10, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# # Import LA boundaries for England and Wales 
# borough_boundaries20 <-
#   st_read("C:/Geographical/LA_UK_boundaries/Local_Authority_Districts_(December_2020)_UK_BGC.shp", quiet = TRUE)

# Import LA boundaries for England and Wales 
borough_boundaries20 <-
  st_read("C:/Geographical/Geographies for Rent data from Yiran/ONS_rents_data_GIS_boundary/ONS_Rents_LAs_allEng_GIS_boundary.shp", quiet = TRUE)


## Now doing map just for area around London for 2011 to 2021

# Import Region boundaries for UK

south_region_boundaries <-
  st_read("C:/Geographical/England_Region_Boundaries/RGN_DEC_2022_EN_BUC.shp", quiet = TRUE) %>%
    mutate(London = ifelse((RGN22CD=="E12000007"), "yes", "no")) %>%
    filter(RGN22CD=="E12000006" | RGN22CD=="E12000007" | RGN22CD=="E12000008" )

change_2011to2021_geog_ed <- LA_2011and2021_agezeroand10_change %>% 
  left_join(borough_boundaries20, by=c("ladcode21"="Area_Code")) %>%
  mutate(Perc_Cat = cut(Change_2011to2021, breaks = c(-45, -28, -16, -5, 5, 16, 28, 50),
                             right=FALSE,
                             labels = c("-45.0 -",
                                        "-28.0 -",
                                        "-16.0 -",
                                        " -5.0 -",
                                        "  5.0 -",
                                        " 16.0 -",
                                        " 28.0+"))) %>%
  data.frame()
  

londonmap7_diverge2 = c('#63c5b5','#96d3c8','#c3e1db','#eeeeee','#d2b4d6','#b47bbe','#943fa6')

change_2011to2021_map_london <- change_2011to2021_geog_ed %>%
   ggplot()+
   geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.1, colour = "black" ) +
  geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
   theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
 theme(legend.text = element_text(size=16)) +
  theme(legend.title = element_text(size=16)) +
  theme(legend.key.height= unit(1, 'cm'),
        legend.key.width= unit(0.7, 'cm')) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank(),
        panel.border = element_rect(colour = "black", fill=NA, size=2)) +
  scale_fill_manual("% change", values = londonmap7_diverge2) + 
  labs(title= "Inter-census cohort change (<1 y.o in 2011 to 10 y.o. in 2021)", 
              subtitle = "Using MYE instead of census data",
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
   labs(fill = "% change") + 
  guides(alpha="none") +
  coord_sf(xlim = c(480000,580000), ylim = c(130000, 220000))
  
change_2011to2021_map_london

ggsave (filename = (paste0(chart_dir, "change_2011to2021_map_london.png")),
         plot = change_2011to2021_map_london,
         device = "png",
         dpi=600,
         width = 9,
         units = "in")


```

```{r fig_pop_change_cohort_10_B, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Map for report

change_2011to2021_map_london_rep <- change_2011to2021_geog_ed %>%
   ggplot()+
   geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.1, colour = "black" ) +
  geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
   theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
 theme(legend.text = element_text(size=16)) +
  theme(legend.title = element_text(size=16)) +
  theme(legend.key.height= unit(1, 'cm'),
        legend.key.width= unit(0.7, 'cm')) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank(),
        panel.border = element_rect(colour = "black", fill=NA, size=2)) +
  scale_fill_manual("% change", values = londonmap7_diverge2) + 
#  labs(title= "Inter-census cohort change (<1 y.o in 2011 to 10 y.o. in 2021)", 
#              subtitle = "Using MYE instead of census data",
#       caption = paste0("Source: Home Office, Chart: GLA demography")) +
   labs(fill = "% change") + 
  guides(alpha="none") +
  coord_sf(xlim = c(480000,580000), ylim = c(130000, 220000))
  
change_2011to2021_map_london_rep

ggsave (filename = "C:/Families/Charts_for_Daryl/22_A1_change_2011to2021_map_london.svg",
         plot = change_2011to2021_map_london_rep,
         device = "svg",
         dpi=600,
         width = 9,
         units = "in")

ggsave (filename = "C:/Families/Charts_for_Daryl/22_A1_change_2011to2021_map_london.png",
         plot = change_2011to2021_map_london_rep,
         device = "png",
         dpi=600,
         width = 9,
         units = "in")

```

```{r fig_pop_change_cohort_11, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Import LA boundaries for England and Wales - trying with 2015 data
borough_boundaries15 <-
  st_read("C:/Geographical/LA_UK_boundaries/Local_Authority_Districts_(December_2015)_Boundaries.shp", quiet = TRUE)

## Now doing map just for area around London for earlier change

change_2001to2011_geog_ed <- LA_2001and2011_agezeroand10_change %>% 
  left_join(borough_boundaries15, by=c("ladcode18"="lad15cd")) %>%
  mutate(Perc_Cat = cut(Change_2001to2011, breaks = c(-45, -28, -16, -5, 5, 16, 28, 50),
                             right=FALSE,
                             labels = c(" -45.0 - -28.01",
                                        " -28.0 - -16.01",
                                        " -16.0 - -5.01",
                                        " -5.0  -  4.99",
                                        "  5.0  - 15.99",
                                        " 16.0  - 27.99",
                                        " 28.0  - 50.00"))) %>%
  data.frame()


londonmap7_diverge2 = c('#63c5b5','#96d3c8','#c3e1db','#eeeeee','#d2b4d6','#b47bbe','#943fa6')

# Import Region boundaries for UK

south_region_boundaries <-
  st_read("C:/Geographical/England_Region_Boundaries/RGN_DEC_2022_EN_BUC.shp", quiet = TRUE) %>%
    mutate(London = ifelse((RGN22CD=="E12000007"), "yes", "no")) %>%
    filter(RGN22CD=="E12000006" | RGN22CD=="E12000007" | RGN22CD=="E12000008" )


change_2001to2011_map_london <- change_2001to2011_geog_ed %>%
   ggplot()+
  # geom_point(aes(x=BNG_E, y=BNG_N,
  #                text = paste("LA name: ",  laname18,
  #                             "<br>Percent change: ",
  #                             formatC(Change_2001to2011, format="f", big.mark=",", digits=2))),
  #            alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
   geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.1, colour = "black" ) +
  geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
   theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank(),
  panel.border = element_rect(colour = "black", fill=NA, size=2))+
  scale_fill_manual(values = londonmap7_diverge2) + 
  labs(title= "Inter-census cohort change (<1 y.o in 2001 to 10 y.o. in 2011)", 
              subtitle = "Using MYE instead of census data",
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
  labs(fill = "% change") + 
  guides(alpha="none") +
  coord_sf(xlim = c(480000,580000), ylim = c(130000, 220000))

change_2001to2011_map_london


ggsave (filename = (paste0(chart_dir, "change_2001to2011_map_london.png")),
         plot = change_2001to2011_map_london,
         device = "png",
         dpi=600,
         width = 9,
         units = "in")



```
```{r fig_pop_change_cohort_11_B, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Map for report

change_2001to2011_map_london_rep <- change_2001to2011_geog_ed %>%
   ggplot()+
  # geom_point(aes(x=BNG_E, y=BNG_N,
  #                text = paste("LA name: ",  laname18,
  #                             "<br>Percent change: ",
  #                             formatC(Change_2001to2011, format="f", big.mark=",", digits=2))),
  #            alpha = 0) +   # alpha = 0 ensures that points are not actually plotted
   geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.1, colour = "black" ) +
  geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
   theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank(),
  panel.border = element_rect(colour = "black", fill=NA, size=2))+
  scale_fill_manual(values = londonmap7_diverge2) + 
#  labs(title= "Inter-census cohort change (<1 y.o in 2001 to 10 y.o. in 2011)", 
#              subtitle = "Using MYE instead of census data",
#       caption = paste0("Source: Home Office, Chart: GLA demography")) +
  theme(legend.position="none") +
  guides(alpha="none") +
  coord_sf(xlim = c(480000,580000), ylim = c(130000, 220000))

change_2001to2011_map_london_rep

ggsave (filename = "C:/Families/Charts_for_Daryl/22_A2_change_2001to2011_map_london.svg",
         plot = change_2001to2011_map_london_rep,
         device = "svg",
         dpi=600,
         width = 9,
         units = "in")

ggsave (filename = "C:/Families/Charts_for_Daryl/22_A2_change_2001to2011_map_london.png",
         plot = change_2001to2011_map_london_rep,
         device = "png",
         dpi=600,
         width = 9,
         units = "in")


```


```{r setup10, include=FALSE, echo=FALSE, warning=FALSE, message=FALSE}

#-----------------------------------------------------------------------
## Compare 0 year olds in 2011 with 10 year olds in 2021


## Compare 0-10 year olds in 2011 with 0-10 year olds in 2021

LA_2011zerototen <- input_2011and2021data %>% 
  mutate(pop2011zero = X2011) %>%
  filter(age < 11) %>%  
   group_by(ladcode21, laname21) %>% 
  summarise(agg_X2011 = sum(X2011)) %>%
  data.frame() 

LA_2021zerototen <- input_2011and2021data %>% 
  mutate(pop2021ten = X2021) %>%
  filter(age < 11) %>%  
 group_by(ladcode21, laname21) %>% 
  summarise(agg_X2021 = sum(X2021)) %>%
  data.frame()

# Merge the two datasets

LA_2011and2021zerototen <- LA_2011zerototen  %>%
  left_join(LA_2021zerototen, by=c("ladcode21"="ladcode21", "laname21"="laname21")) %>% 
  data.frame() 

# calculate change
LA_2011and2021_agezeroto10_change <- LA_2011and2021zerototen %>% 
  group_by(ladcode21, laname21) %>% 
  mutate(Change_2011to2021 = ((agg_X2021 - agg_X2011)*100/agg_X2011)) %>%
  drop_na() %>%
  data.frame()

#----------------------------

quantile(LA_2011and2021_agezeroto10_change$Change_2011to2021, probs = seq(0, 1, 1/5))

```


```{r fig_pop_change_zerototen, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Import LA boundaries for England and Wales 
borough_boundaries20 <-
  st_read("C:/Geographical/Geographies for Rent data from Yiran/ONS_rents_data_GIS_boundary/ONS_Rents_LAs_allEng_GIS_boundary.shp", quiet = TRUE)


## Now doing map just for area around London for 2011 to 2021 
#Changesd categories on 17th Feb as not plotting lowest category

quantile(LA_2011and2021_agezeroto10_change$Perc_cat)

# Import Region boundaries for UK

south_region_boundaries <-
  st_read("C:/Geographical/England_Region_Boundaries/RGN_DEC_2022_EN_BUC.shp", quiet = TRUE) %>%
    mutate(London = ifelse((RGN22CD=="E12000007"), "yes", "no")) %>%
    filter(RGN22CD=="E12000006" | RGN22CD=="E12000007" | RGN22CD=="E12000008" )

change_2011to2021_zerototen_geog <- LA_2011and2021_agezeroto10_change %>% 
  left_join(borough_boundaries20, by=c("ladcode21"="Area_Code")) %>%
  #mutate(Perc_Cat = cut(Change_2011to2021, breaks = c(-45, -28, -16, -5, 5, 16, 28, 50),
   mutate(Perc_Cat = cut(Change_2011to2021, breaks = c(-35, -20, -10, -5, 5, 10, 20, 35),
                             right=FALSE,
                             labels = c("-35.0 -",
                                        "-20.0 -",
                                        "-10.0 -",
                                        " -5.0 -",
                                        "  5.0 -",
                                        " 10.0 -",
                                        " 20.0+"))) %>%
  data.frame()


quantile(LA_2011and2021_agezeroto10_change$Change_2011to2021)


londonmap7_diverge2 = c('#63c5b5','#96d3c8','#c3e1db','#eeeeee','#d2b4d6','#b47bbe','#943fa6')
londonmap6_diverge2 = c('#96d3c8','#c3e1db','#eeeeee','#d2b4d6','#b47bbe','#943fa6')


change_2011to2021_zerototen_map_london <- change_2011to2021_zerototen_geog %>%
   ggplot()+
   geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.1, colour = "black" ) +
  geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
   theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.text = element_text(size=16)) +
  theme(legend.title = element_text(size=16)) +
  theme(legend.key.height= unit(1, 'cm'),
        legend.key.width= unit(0.7, 'cm')) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank(),
  panel.border = element_rect(colour = "black", fill=NA, size=2))+
  scale_fill_manual(values = londonmap7_diverge2) + 
  labs(title= "Inter-census change (2011 - 2021) in population age 0 - 10 y.o.", 
              subtitle = "Using MYE instead of census data",
       caption = paste0("Source: Home Office, Chart: GLA demography")) +
   labs(fill = "% change") + 
  guides(alpha="none") +
  coord_sf(xlim = c(480000,580000), ylim = c(130000, 220000))

change_2011to2021_zerototen_map_london

ggsave (filename = (paste0(chart_dir, "change_2011to2021_zerototen_map_london.png")),
         plot = change_2011to2021_zerototen_map_london,
         device = "png",
         dpi=600,
         width = 9,
         units = "in")


```

```{r fig_pop_change_zerototen_B, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Map for report 

change_2011to2021_zerototen_map_london_rep <- change_2011to2021_zerototen_geog %>%
   ggplot()+
   geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.1, colour = "black" ) +
  geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
   theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.text = element_text(size=16)) +
  theme(legend.title = element_text(size=16)) +
  theme(legend.key.height= unit(1, 'cm'),
        legend.key.width= unit(0.7, 'cm')) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank(),
  panel.border = element_rect(colour = "black", fill=NA, size=2))+
  scale_fill_manual(values = londonmap7_diverge2) + 
#  labs(title= "Inter-census change (2011 - 2021) in population age 0 - 10 y.o.", 
#              subtitle = "Using MYE instead of census data",
#       caption = paste0("Source: Home Office, Chart: GLA demography")) +
   labs(fill = "% change") + 
  guides(alpha="none") +
  coord_sf(xlim = c(480000,580000), ylim = c(130000, 220000))

change_2011to2021_zerototen_map_london_rep

ggsave (filename = "C:/Families/Charts_for_Daryl/31_A_change_2011to2021_zerototen_map_london.svg",
         plot = change_2011to2021_zerototen_map_london_rep,
         device = "svg",
         dpi=600,
         width = 9,
         units = "in")

ggsave (filename = "C:/Families/Charts_for_Daryl/31_A_change_2011to2021_zerototen_map_london.png",
         plot = change_2011to2021_zerototen_map_london_rep,
         device = "png",
         dpi=600,
         width = 9,
         units = "in")

```


```{r fig_pop_change_donal, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Import census population data

input_donaldata <- fread(paste0(data_dir,"ftb_hhcomp_21_qs118_11_uv006_01.csv"))%>% 
  data.frame()

 ## aggregating the dataset to total number of households with dependent children - i.e. collapsing the categorical detail

#total_households_la <- input_donaldata[, .(value_21 = sum(value_21), value_11 = sum(value_11), value_01 = sum(value_01)),        by = list(lad22cd)]

  ## calculating the change from 2011 to 2021

#total_households_la[, change_2111 := value_21 - value_11]


## deriving a categorical variable for the variable we're plotting, to keep with existing style of maps in the report

#cut_breaks <- c(-3000, -1500, -1, 0, 1500, 3000, 4500, 6000)
#cut_labels <- c("-3000 to -1500", "-1499 to -1", "0", "1 to 1500", "1501 to 3000", "3001 to 4500", "4501 to 6000")

#total_households_la[, change_2111_cat := cut(change_2111,
      #                                       breaks = cut_breaks,
        #                                     labels = cut_labels)]

## joining on the Borough boundaries for plotting, and converting the data.table to an sf object

#setkey(total_households_la, "lad22cd")

#total_households_la <- st_as_sf(borough_bounds[total_households_la])

DepChildren_Change <- input_donaldata  %>%
  group_by(lad22cd, lad22nm) %>% 
  summarise(sum_value21 = sum(value_21), sum_value11 = sum(value_11), sum_value01 = sum(value_01)) %>%
  mutate(changePerc = ((sum_value21 - sum_value11)*100/sum_value11)) %>%
    drop_na() %>%
  data.frame()

#quantile(LA_2011and2021_agezeroto10_change$Change_2011to2021, probs = seq(0, 1, 1/5))

# summary(DepChildren_Change$changePerc)

south_region_boundaries <-
  st_read("C:/Geographical/England_Region_Boundaries/RGN_DEC_2022_EN_BUC.shp", quiet = TRUE) %>%
    mutate(London = ifelse((RGN22CD=="E12000007"), "yes", "no")) %>%
    filter(RGN22CD=="E12000006" | RGN22CD=="E12000007" | RGN22CD=="E12000008" )


# Import LA boundaries for England and Wales
borough_boundaries <-
  st_read("C:/Migration/Migration_R/DATA/Domestic/copied_from_Qdrive_20220614/geographical/LAD_DEC_2021_GB_BUC.shp", quiet = TRUE)

change_2011to2021_depChildren_geog <- DepChildren_Change %>% 
  left_join(borough_boundaries, by=c("lad22cd"="LAD21CD")) %>%
 # mutate(Perc_Cat = cut(changePerc, breaks = c(-15, -4, -2, 2, 6, 10, 50),
  mutate(Perc_Cat = cut(changePerc, breaks = c(-20, -10, -5, -2, 2, 7, 12, 40),
                             right=FALSE,
                             labels = c("-20.0 -",
                                        "-10.0 -",
                                        "- 5.0 -",
                                        "- 2.0 -",
                                        "  2.0 -",
                                        "  7.0 -",
                                        " 12.0+"))) %>%
  data.frame()                  
  

#quantile(change_2011to2021_depChildren_geog$changePerc, probs = seq(0, 1, 1/5))
                    
## making a map showing the change in number of households with dependent children across London by Borough

londonmap6_diverge2 = c('#96d3c8','#c3e1db','#eeeeee','#d2b4d6','#b47bbe','#943fa6')
londonmap7_diverge2 = c('#63c5b5','#96d3c8','#c3e1db','#eeeeee','#d2b4d6','#b47bbe','#943fa6')
 
#jpeg(filename = "output_plots/1_map_total_families.jpg", 
 #    width = 8, height = 6, units = "in", res = 850)
change_2011to2021_depchildren_map_london <- change_2011to2021_depChildren_geog %>%
  ggplot() + 
  geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.1, colour = "black" ) +
  # geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
   theme(plot.title = element_text(size = 16, hjust = 0.5)) +

  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right") +
  #theme(legend.title = element_blank()) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  theme(panel.background = element_blank()) +
  theme(plot.caption = element_text (hjust = 0)) +
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(plot.subtitle = element_text(size = 12, hjust= 0.5)) +
  theme(plot.caption = element_text(size = 10, hjust= 0)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank()) +
   scale_fill_manual("% change", values = londonmap7_diverge2,
                    limits = levels(change_2011to2021_depChildren_geog$Perc_Cat)) +  
    theme(legend.text = element_text(size=16)) +
  theme(legend.title = element_text(size=16)) +
  theme(legend.key.height= unit(1, 'cm'),
        legend.key.width= unit(0.7, 'cm')) +
   labs(title = "Number of households with dependent children", 
       subtitle = "Change from Census 2011 to Census 2021",
       caption = "Source: Census 2011 & Census 2021, Chart: GLA demography") 
 change_2011to2021_depchildren_map_london 
 
 
ggsave (filename = (paste0(chart_dir, " change_2011to2021_depchildren_map_london.png")),
         plot =  change_2011to2021_depchildren_map_london ,
         device = "png",
         dpi=600,
         width = 9,
         units = "in")
 

```

```{r fig_pop_change_donal_B, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

# Map for report

change_2011to2021_depchildren_map_london_rep <- change_2011to2021_depChildren_geog %>%
  ggplot() + 
  geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.1, colour = "black" ) +
  # geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
   theme(plot.title = element_text(size = 16, hjust = 0.5)) +

  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right") +
  #theme(legend.title = element_blank()) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  theme(panel.background = element_blank()) +
  theme(plot.caption = element_text (hjust = 0)) +
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(plot.subtitle = element_text(size = 12, hjust= 0.5)) +
  theme(plot.caption = element_text(size = 10, hjust= 0)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank()) +
  scale_fill_manual("% change", values = londonmap7_diverge2,
                    limits = levels(change_2011to2021_depChildren_geog$Perc_Cat)) +  
    theme(legend.text = element_text(size=16)) +
  theme(legend.title = element_text(size=16)) +
  theme(legend.key.height= unit(1, 'cm'),
        legend.key.width= unit(0.7, 'cm')) 
#+
#   labs(title = "Number of households with dependent children", 
#       subtitle = "Change from Census 2011 to Census 2021",
#       caption = "Source: Census 2011 & Census 2021, Chart: GLA demography") 
 change_2011to2021_depchildren_map_london_rep 
 

ggsave (filename = "C:/Families/Charts_for_Daryl/31_B_change_2011to2021_depchildren_map_london.svg",
         plot =  change_2011to2021_depchildren_map_london_rep,
         device = "svg",
         dpi=600,
         width = 9,
         units = "in")
 

```

```{r fig_pop_change_NonDepChildren, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Map showing the change in number non-dependent children across London by Borough

## NB THIS ISN'T USED IN REPORT - it's about numbers not households

## Import data

input_Non_dep_childrendata <- fread(paste0(data_dir,"Non_dependent_children_Change_LondonOnly.csv"))%>% 
  data.frame()

#quantile(input_Non_dep_childrendata$Non_dep_change, probs = seq(0, 1, 1/5))

#summary(input_Non_dep_childrendata$Non_dep_change)

# Import LA boundaries for England and Wales
borough_boundaries <-
  st_read("C:/Migration/Migration_R/DATA/Domestic/copied_from_Qdrive_20220614/geographical/LAD_DEC_2021_GB_BUC.shp", quiet = TRUE)

change_nondepchildren_geog <- input_Non_dep_childrendata %>% 
  left_join(borough_boundaries, by=c("Code" = "LAD21CD")) %>%
  mutate(Perc_Cat = cut(Non_dep_change, breaks = c(10, 22, 28, 34, 50),
                             right=FALSE,
                             labels = c("10.0 -",
                                        "22.0 -",
                                        "28.0 -",
                                        "34.0 -"))) %>%
  data.frame()                  
  
 

catgreen4 = c('#eeeeee', '#acc1aa', '#739272', '#4a6349')
 

change_nondepchildren  <- change_nondepchildren_geog  %>%
  ggplot() + 
  geom_sf(aes(geometry=geometry, fill=Perc_Cat),lwd = 0.1, colour = "black" ) +
  # geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
   theme(plot.title = element_text(size = 16, hjust = 0.5)) +

  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right") +
  #theme(legend.title = element_blank()) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  theme(panel.background = element_blank()) +
  theme(plot.caption = element_text (hjust = 0)) +
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(plot.subtitle = element_text(size = 12, hjust= 0.5)) +
  theme(plot.caption = element_text(size = 10, hjust= 0)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank()) +
  scale_fill_manual("% change", values = catgreen4) + 
    theme(legend.text = element_text(size=16)) +
  theme(legend.title = element_text(size=16)) +
  theme(legend.key.height= unit(1, 'cm'),
        legend.key.width= unit(0.7, 'cm')) +
   labs(title = "Numbers of non-dependent children", 
       subtitle = "Change from Census 2011 to Census 2021",
       caption = "Source: Census 2011 & Census 2021, Chart: GLA demography") 
change_nondepchildren
 
 
ggsave (filename = (paste0(chart_dir, " change_nondepchildren.png")),
         plot =  change_nondepchildren ,
         device = "png",
         dpi=600,
         width = 9,
         units = "in")
 

```


```{r fig_pop_change_nondepHH, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## making a map showing the number of households with non-dependent children across London by Borough

## Import data

input_non_dep_hh_2021 <- fread(paste0(data_dir,"Non_dep_HH_2021.csv"))%>% 
  data.frame()


# Import LA boundaries for England and Wales 
borough_boundaries20 <-
  st_read("C:/Geographical/Geographies for Rent data from Yiran/ONS_rents_data_GIS_boundary/ONS_Rents_LAs_allEng_GIS_boundary.shp", quiet = TRUE)


# quantile(input_non_dep_hh_2021$Sum)

# Import Region boundaries for UK

south_region_boundaries <-
  st_read("C:/Geographical/England_Region_Boundaries/RGN_DEC_2022_EN_BUC.shp", quiet = TRUE) %>%
    mutate(London = ifelse((RGN22CD=="E12000007"), "yes", "no")) %>%
    filter(RGN22CD=="E12000006" | RGN22CD=="E12000007" | RGN22CD=="E12000008" )

non_dep_hh_2021_geog <- input_non_dep_hh_2021 %>% 
  left_join(borough_boundaries20, by=c("Area.code"="Area_Code")) %>%
    mutate(HHCat = cut(Sum, breaks = c(3, 9, 10, 12, 20),
                             right=FALSE,
                             labels = c(" 3 -",
                                        " 9 -",
                                        "10 -",
                                        "12 -"))) %>%
  data.frame()


#quantile(LA_2011and2021_agezeroto10_change$Change_2011to2021)


catgreen4 = c('#eeeeee', '#acc1aa', '#739272', '#4a6349')


non_dep_hh_2021_map_london <- non_dep_hh_2021_geog %>%
   ggplot()+
   geom_sf(aes(geometry=geometry, fill=HHCat),lwd = 0.1, colour = "black" ) +
  geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
   theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.text = element_text(size=16)) +
  theme(legend.title = element_text(size=16)) +
  theme(legend.key.height= unit(1, 'cm'),
        legend.key.width= unit(0.7, 'cm')) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank(),
  panel.border = element_rect(colour = "black", fill=NA, size=2))+
  scale_fill_manual(values = catgreen4) + 
  labs(title= "Per cent of couple and lone-parent households with all non-dependent children, 2021", 
 caption = paste0("Source: Home Office, Chart: GLA demography")) +
   labs(fill = "% households") + 
  guides(alpha="none") +
  coord_sf(xlim = c(480000,580000), ylim = c(130000, 220000))

non_dep_hh_2021_map_london

ggsave (filename = (paste0(chart_dir, "non_dep_hh_2021_map_london.png")),
         plot = non_dep_hh_2021_map_london,
         device = "png",
         dpi=600,
         width = 9,
         units = "in")


```


```{r fig_pop_depHH, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## making a map showing the number of households with dependent children across London by Borough

## Import data

input_dep_hh_2021 <- fread(paste0(data_dir,"Dep_HH_2021.csv"))%>% 
  data.frame()


# Import LA boundaries for England and Wales 
borough_boundaries20 <-
  st_read("C:/Geographical/Geographies for Rent data from Yiran/ONS_rents_data_GIS_boundary/ONS_Rents_LAs_allEng_GIS_boundary.shp", quiet = TRUE)


# quantile(input_dep_hh_2021$Sum)

# Import Region boundaries for UK

south_region_boundaries <-
  st_read("C:/Geographical/England_Region_Boundaries/RGN_DEC_2022_EN_BUC.shp", quiet = TRUE) %>%
    mutate(London = ifelse((RGN22CD=="E12000007"), "yes", "no")) %>%
    filter(RGN22CD=="E12000006" | RGN22CD=="E12000007" | RGN22CD=="E12000008" )

dep_hh_2021_geog <- input_dep_hh_2021 %>% 
  left_join(borough_boundaries20, by=c("Area.code"="Area_Code")) %>%
    mutate(HHCat = cut(Sum, breaks = c(7, 23, 26, 29, 40),
                             right=FALSE,
                             labels = c(" 7 -",
                                        "23 -",
                                        "26 -",
                                        "29 -"))) %>%
  data.frame()


#quantile(LA_2011and2021_agezeroto10_change$Change_2011to2021)


catgreen4 = c('#eeeeee', '#acc1aa', '#739272', '#4a6349')

dep_hh_2021_map_london <- dep_hh_2021_geog %>%
   ggplot()+
   geom_sf(aes(geometry=geometry, fill=HHCat),lwd = 0.1, colour = "black" ) +
  geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
   theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.text = element_text(size=16)) +
  theme(legend.title = element_text(size=16)) +
  theme(legend.key.height= unit(1, 'cm'),
        legend.key.width= unit(0.7, 'cm')) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank(),
  panel.border = element_rect(colour = "black", fill=NA, size=2))+
  scale_fill_manual(values = catgreen4) + 
  labs(title= "Per cent of couple and lone-parent households with dependent children, 2021", 
 caption = paste0("Source: Home Office, Chart: GLA demography")) +
   labs(fill = "% households") + 
  guides(alpha="none") +
  coord_sf(xlim = c(480000,580000), ylim = c(130000, 220000))
dep_hh_2021_map_london

ggsave (filename = (paste0(chart_dir, "dep_hh_2021_map_london.png")),
         plot = dep_hh_2021_map_london,
         device = "png",
         dpi=600,
         width = 9,
         units = "in")


```

```{r fig_pop_depHH_B, fig.height = 9, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

## Map for report


dep_hh_2021_geog <- input_dep_hh_2021 %>% 
  left_join(borough_boundaries20, by=c("Area.code"="Area_Code")) %>%
    mutate(HHCat = cut(Sum, breaks = c(7, 23, 26, 29, 40),
                             right=FALSE,
                             labels = c(" 7 -",
                                        "23 -",
                                        "26 -",
                                        "29+"))) %>%
  data.frame()


#quantile(LA_2011and2021_agezeroto10_change$Change_2011to2021)


catgreen4 = c('#eeeeee', '#acc1aa', '#739272', '#4a6349')

dep_hh_2021_map_london_rep <- dep_hh_2021_geog %>%
   ggplot()+
   geom_sf(aes(geometry=geometry, fill=HHCat),lwd = 0.1, colour = "black" ) +
  geom_sf(data = south_region_boundaries, aes(x=LONG, y=LAT, geometry=geometry), alpha = 0.01, lwd = 0.7, colour = "black")+
   theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.position = "right")+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+
  theme(panel.background = element_blank())+
  theme(plot.caption = element_text (hjust = 0))+
  theme(plot.title = element_text(size = 16, hjust = 0.5)) +
  theme(legend.text = element_text(size=16)) +
  theme(legend.title = element_text(size=16)) +
  theme(legend.key.height= unit(1, 'cm'),
        legend.key.width= unit(0.7, 'cm')) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(), 
        axis.ticks.y = element_blank(),
  panel.border = element_rect(colour = "black", fill=NA, size=2))+
  scale_fill_manual(values = catgreen4) + 
#  labs(title= "Per cent of couple and lone-parent households with dependent children, 2021", 
 #caption = paste0("Source: Home Office, Chart: GLA demography")) +
   labs(fill = "% households") + 
  guides(alpha="none") +
  coord_sf(xlim = c(480000,580000), ylim = c(130000, 220000))
dep_hh_2021_map_london_rep

ggsave (filename = "C:/Families/Charts_for_Daryl/31_C_dep_hh_2021_map_london.svg",
         plot = dep_hh_2021_map_london_rep,
         device = "svg",
         dpi=600,
         width = 9,
         units = "in")

ggsave (filename = "C:/Families/Charts_for_Daryl/31_C_dep_hh_2021_map_london.png",
         plot = dep_hh_2021_map_london_rep,
         device = "png",
         dpi=600,
         width = 9,
         units = "in")


```
