---
title: "Schools analysis - Prim and Sec - 7 June 2024"
output: 
  html_document:
    css: Wil_style.css
    theme: default
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
always_allow_html: yes
---

```{r setup1, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(zoo)
library(data.table)
library(tidyverse)
library(gglaplot)
library(ggplot2)
library(scales)
library(readxl)
library(knitr)
library(sf)
library(sp)
library(kableExtra)
library(magick)
library(plotly)    
library(RColorBrewer)
library(htmltools)
library(prettydoc)
library(rmdformats)
library(ggrepel)

library(devtools)
devtools::install_github("Greater-London-Authority/gglaplot")

chart_dir <- 'CHARTS/'

data_dir <- 'DATA/'

# Disable scientific notation
options(scipen=999)


```


```{r setup3, include=FALSE}

# SCHOOLS DATA For children in London, using data that Ben provided.

boroughcodes <- fread(paste0(data_dir,"InnerLondon.csv")) %>%   
  data.frame

cityORcounty_codes <- fread(paste0(data_dir,"cityORcounty.csv")) %>%   
  data.frame

# Input data for headcounts of children and merge with city/county file

input_all_schools_data <- fread(paste0(data_dir,"pupils_lad_type_age_2009to22.csv")) %>%
  full_join(cityORcounty_codes, by=c("new_la_code"= "la_code"), keep = TRUE)%>% 
  mutate(across(c(cityORcounty_code, cityORcounty_name), factor)) %>%
 data.frame() 


```


```{r fig_London_Prim_schools_line_1, fig.height = 5.56, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

catcolour2 = rev(c('#d82222', '#6da7de'))

# Plot by individual borough

agg_input_london_SF_primary_schools_borough <- input_all_schools_data %>%
  filter(grepl('E09', new_la_code)) %>%
  filter(la_name.x != "City of London") %>%
  filter(age < 11) %>%
  filter(type == "State-funded") %>%
  group_by(period_start, la_name.x, cityORcounty_name, period2) %>% 
  summarise(agg_full_time = sum(full_time)) %>%
# mutate(Year = as.character(year)) %>%
  data.frame()

# Index aggregated values to 2009 value

London_SF_prim_schools_agg_ind2009_borough <- agg_input_london_SF_primary_schools_borough %>%
   group_by(la_name.x) %>% 
   mutate(indexed_headcount = (agg_full_time/first(agg_full_time))*100) %>% 
  data.frame()

prim_schools_highlight <- highlight_key(London_SF_prim_schools_agg_ind2009_borough, ~la_name.x)

prim_schools_line <- ggplot(prim_schools_highlight, aes(x = period_start, y = indexed_headcount, group = la_name.x, color = cityORcounty_name
             , text = paste("Year  :", period_start,
                            "<br>Zone : ", la_name.x,
                            "<br>Headcount : ", agg_full_time,
                            "<br>Head count as % of 2009 : ", round(indexed_headcount, digits = 0))
  )) +
  theme_gla() +
  geom_line() + 
  geom_hline(yintercept=100)+
 # scale_y_continuous(breaks = seq(88, 102, 2)) + #, limits = c(88, 102)) +
 scale_color_manual(name='Zone:', values = rev(catcolour2)) +
  labs(title= "Primary schools headcount, London, 2009- 2022, indexed to 2009 value", 
       caption = paste0("Source: ONS, Chart: GLA demography"))


prim_schools_line_int <- ggplotly(prim_schools_line, tooltip = "text") %>%
  style(hoverlabel = list(bgcolor = "white")) %>%
   layout(legend = list(orientation = 'h', x = 0, y = 1.0)) %>%
  layout(title= list(x = 0.05,
                     text = "<b>Primary schools headcount, indexed to 2009, London boroughs <b>", 
                     font=list(size = 15, family = "Arial"))) %>%
 layout(title= list(x = 0.05,
                     text = "<b>Secondary schools headcount, indexed to 2009, London boroughs <b>",
                     font=list(size = 15, family = "Arial"))) %>%
  layout(legend = list(title = list(text = ""), font=list(size = 15, family = "Arial", color = "black", fontface = "bold"))) %>% 
  layout(xaxis = list(tickfont = list(size = 12, family = "Arial")), 
         yaxis = list(tickfont = list(size = 12, family = "Arial"))) %>%
  layout(hoverlabel = list(align = "left")) %>%
    layout(margin = list(l = 100, r = 100,  b =0,  t = 100,  pad = 4))



highlight(prim_schools_line_int, on = "plotly_hover", off = "plotly_deselect", alpha = 1, selected = attrs_selected(showlegend = FALSE) )

```

```{r fig_London_Sec_schools_line_1, fig.height = 5.56, fig.width = 9,  echo=FALSE, warning=FALSE, message=FALSE}

catcolour2 = rev(c('#d82222', '#6da7de'))

# Plot by individual borough

agg_input_london_SF_secondary_schools_borough <- input_all_schools_data %>%
  filter(grepl('E09', new_la_code)) %>%
  filter(la_name.x != "City of London") %>%
  filter(age > 10) %>%
  filter(type == "State-funded") %>%
  group_by(period_start, la_name.x, cityORcounty_name, period2) %>% 
  summarise(agg_full_time = sum(full_time)) %>%
# mutate(Year = as.character(year)) %>%
  data.frame()

# Index aggregated values to 2009 value

London_SF_sec_schools_agg_ind2009_borough <- agg_input_london_SF_secondary_schools_borough %>%
   group_by(la_name.x) %>% 
   mutate(indexed_headcount = (agg_full_time/first(agg_full_time))*100) %>% 
  data.frame()

sec_schools_highlight <- highlight_key(London_SF_sec_schools_agg_ind2009_borough, ~la_name.x)

sec_schools_line <- ggplot(sec_schools_highlight, aes(x = period_start, y = indexed_headcount, group = la_name.x, color = cityORcounty_name
             , text = paste("Year  :", period_start,
                            "<br>Zone : ", la_name.x,
                            "<br>Headcount : ", agg_full_time,
                            "<br>Head count as % of 2009 : ", round(indexed_headcount, digits = 0))
  )) +
  theme_gla() +
  geom_line() + 
  geom_hline(yintercept=100)+  
#  geom_blank(aes(color = cityORcounty_name)) +
 # scale_y_continuous(breaks = seq(88, 102, 2)) + #, limits = c(88, 102)) +
 scale_color_manual(name='Zone:', values = rev(catcolour2)) +
  labs(title= "Secondary schools headcount, London, 2009- 2022, indexed to 2009 value", 
       caption = paste0("Source: ONS, Chart: GLA demography"))

sec_schools_line_int <- ggplotly(sec_schools_line, tooltip = "text") %>%
  style(hoverlabel = list(bgcolor = "white")) %>%
  layout(legend = list(orientation = 'h', x = 0, y = 1.0)) %>%
  layout(title= list(x = 0.05,
                     text = "<b>Secondary schools headcount, indexed to 2009, London boroughs <b>",
                     font=list(size = 15, family = "Arial"))) %>%
  layout(legend = list(title = list(text = ""), font=list(size = 15, family = "Arial", color = "black", fontface = "bold"))) %>% 
  layout(xaxis = list(tickfont = list(size = 12, family = "Arial")), 
        yaxis = list(tickfont = list(size = 12, family = "Arial"))) %>%
  layout(hoverlabel = list(align = "left")) %>%
#  layout(annotations = list(x = 0.05, y = -0.05, text = "Source: ONS, Chart: GLA demography", 
#                            showarrow = F, xref='paper', yref='paper', 
#                            font=list(size=14)) ) %>%
  layout(margin = list(l = 100, r = 100,  b =0,  t = 100,  pad = 4))





highlight(sec_schools_line_int, on = "plotly_hover", off = "plotly_deselect", alpha = 1, selected = attrs_selected(showlegend = FALSE) )


```

